// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package org.ai.aidemo.proto;

public final class Demo {
  private Demo() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Demo.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcAssistantMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcAssistantMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcDelta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcDelta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_GrpcFunctionCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_GrpcFunctionCall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcPromptTokensDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcPromptTokensDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcCompletionTokensDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcCompletionTokensDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\007chat.v1\"\222\003\n\017GrpcChatReques" +
      "t\022\r\n\005query\030\001 \001(\t\022\024\n\007session\030\002 \001(\tH\000\210\001\001\022@" +
      "\n\ntoolCallVo\030\003 \001(\0132\'.chat.v1.GrpcChatReq" +
      "uest.GrpcToolCallVoH\001\210\001\001\022\034\n\024isToolCallIn" +
      "Progress\030\004 \001(\010\022\032\n\022isToolCallFinished\030\005 \001" +
      "(\010\032\302\001\n\016GrpcToolCallVo\022\027\n\ntoolCallId\030\001 \001(" +
      "\tH\000\210\001\001\022\031\n\014functionName\030\002 \001(\tH\001\210\001\001\022\032\n\rtoo" +
      "lArguments\030\003 \001(\tH\002\210\001\001\022\033\n\016toolCallResult\030" +
      "\004 \001(\tH\003\210\001\001B\r\n\013_toolCallIdB\017\n\r_functionNa" +
      "meB\020\n\016_toolArgumentsB\021\n\017_toolCallResultB" +
      "\n\n\010_sessionB\r\n\013_toolCallVo\"\275\023\n\032GrpcChatC" +
      "ompletionResponse\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\017\n\007cr" +
      "eated\030\002 \001(\005\022\022\n\005model\030\003 \001(\tH\001\210\001\001\022M\n\007choic" +
      "es\030\004 \003(\0132<.chat.v1.GrpcChatCompletionRes" +
      "ponse.GrpcChatCompletionChoice\022A\n\005usage\030" +
      "\005 \001(\0132-.chat.v1.GrpcChatCompletionRespon" +
      "se.GrpcUsageH\002\210\001\001\022\036\n\021systemFingerprint\030\006" +
      " \001(\tH\003\210\001\001\022\030\n\013serviceTier\030\007 \001(\tH\004\210\001\001\032\275\010\n\030" +
      "GrpcChatCompletionChoice\022\r\n\005index\030\001 \001(\005\022" +
      "g\n\007message\030\002 \001(\0132Q.chat.v1.GrpcChatCompl" +
      "etionResponse.GrpcChatCompletionChoice.G" +
      "rpcAssistantMessageH\000\210\001\001\022Z\n\005delta\030\003 \001(\0132" +
      "F.chat.v1.GrpcChatCompletionResponse.Grp" +
      "cChatCompletionChoice.GrpcDeltaH\001\210\001\001\022\031\n\014" +
      "finishReason\030\004 \001(\tH\002\210\001\001\032\250\003\n\024GrpcAssistan" +
      "tMessage\022?\n\004role\030\001 \001(\0162,.chat.v1.GrpcCha" +
      "tCompletionResponse.GrpcRoleH\000\210\001\001\022\024\n\007con" +
      "tent\030\002 \001(\tH\001\210\001\001\022\035\n\020reasoningContent\030\003 \001(" +
      "\tH\002\210\001\001\022\021\n\004name\030\004 \001(\tH\003\210\001\001\022C\n\ttoolCalls\030\005" +
      " \003(\01320.chat.v1.GrpcChatCompletionRespons" +
      "e.GrpcToolCall\022\024\n\007refusal\030\006 \001(\010H\004\210\001\001\022\\\n\014" +
      "functionCall\030\007 \001(\0132A.chat.v1.GrpcChatCom" +
      "pletionResponse.GrpcToolCall.GrpcFunctio" +
      "nCallH\005\210\001\001B\007\n\005_roleB\n\n\010_contentB\023\n\021_reas" +
      "oningContentB\007\n\005_nameB\n\n\010_refusalB\017\n\r_fu" +
      "nctionCall\032\337\002\n\tGrpcDelta\022?\n\004role\030\001 \001(\0162," +
      ".chat.v1.GrpcChatCompletionResponse.Grpc" +
      "RoleH\000\210\001\001\022\024\n\007content\030\002 \001(\tH\001\210\001\001\022\035\n\020reaso" +
      "ningContent\030\003 \001(\tH\002\210\001\001\022C\n\ttoolCalls\030\004 \003(" +
      "\01320.chat.v1.GrpcChatCompletionResponse.G" +
      "rpcToolCall\022\\\n\014functionCall\030\005 \001(\0132A.chat" +
      ".v1.GrpcChatCompletionResponse.GrpcToolC" +
      "all.GrpcFunctionCallH\003\210\001\001B\007\n\005_roleB\n\n\010_c" +
      "ontentB\023\n\021_reasoningContentB\017\n\r_function" +
      "CallB\n\n\010_messageB\010\n\006_deltaB\017\n\r_finishRea" +
      "son\032\207\003\n\014GrpcToolCall\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\022\n" +
      "\005index\030\002 \001(\005H\001\210\001\001\022P\n\004type\030\003 \001(\0162=.chat.v" +
      "1.GrpcChatCompletionResponse.GrpcToolCal" +
      "l.GrpcToolTypeH\002\210\001\001\022X\n\010function\030\004 \001(\0132A." +
      "chat.v1.GrpcChatCompletionResponse.GrpcT" +
      "oolCall.GrpcFunctionCallH\003\210\001\001\032T\n\020GrpcFun" +
      "ctionCall\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\026\n\targument" +
      "s\030\002 \001(\tH\001\210\001\001B\007\n\005_nameB\014\n\n_arguments\")\n\014G" +
      "rpcToolType\022\013\n\007UNKNOWN\020\000\022\014\n\010FUNCTION\020\001B\005" +
      "\n\003_idB\010\n\006_indexB\007\n\005_typeB\013\n\t_function\032\273\004" +
      "\n\tGrpcUsage\022\030\n\013totalTokens\030\001 \001(\005H\000\210\001\001\022\031\n" +
      "\014promptTokens\030\002 \001(\005H\001\210\001\001\022g\n\023promptTokens" +
      "Details\030\003 \001(\0132E.chat.v1.GrpcChatCompleti" +
      "onResponse.GrpcUsage.GrpcPromptTokensDet" +
      "ailsH\002\210\001\001\022\035\n\020completionTokens\030\004 \001(\005H\003\210\001\001" +
      "\022o\n\027completionTokensDetails\030\005 \001(\0132I.chat" +
      ".v1.GrpcChatCompletionResponse.GrpcUsage" +
      ".GrpcCompletionTokensDetailsH\004\210\001\001\032E\n\027Grp" +
      "cPromptTokensDetails\022\031\n\014cachedTokens\030\001 \001" +
      "(\005H\000\210\001\001B\017\n\r_cachedTokens\032O\n\033GrpcCompleti" +
      "onTokensDetails\022\034\n\017reasoningTokens\030\001 \001(\005" +
      "H\000\210\001\001B\022\n\020_reasoningTokensB\016\n\014_totalToken" +
      "sB\017\n\r_promptTokensB\026\n\024_promptTokensDetai" +
      "lsB\023\n\021_completionTokensB\032\n\030_completionTo" +
      "kensDetails\"T\n\010GrpcRole\022\013\n\007UNKNOWN\020\000\022\n\n\006" +
      "SYSTEM\020\001\022\010\n\004USER\020\002\022\r\n\tASSISTANT\020\003\022\010\n\004TOO" +
      "L\020\004\022\014\n\010FUNCTION\020\005B\005\n\003_idB\010\n\006_modelB\010\n\006_u" +
      "sageB\024\n\022_systemFingerprintB\016\n\014_serviceTi" +
      "er2\\\n\013ChatService\022M\n\nChatStream\022\030.chat.v" +
      "1.GrpcChatRequest\032#.chat.v1.GrpcChatComp" +
      "letionResponse0\001B\027\n\023org.ai.aidemo.protoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chat_v1_GrpcChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_v1_GrpcChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatRequest_descriptor,
        new java.lang.String[] { "Query", "Session", "ToolCallVo", "IsToolCallInProgress", "IsToolCallFinished", });
    internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor =
      internal_static_chat_v1_GrpcChatRequest_descriptor.getNestedTypes().get(0);
    internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor,
        new java.lang.String[] { "ToolCallId", "FunctionName", "ToolArguments", "ToolCallResult", });
    internal_static_chat_v1_GrpcChatCompletionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_v1_GrpcChatCompletionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_descriptor,
        new java.lang.String[] { "Id", "Created", "Model", "Choices", "Usage", "SystemFingerprint", "ServiceTier", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_descriptor.getNestedTypes().get(0);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_descriptor,
        new java.lang.String[] { "Index", "Message", "Delta", "FinishReason", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcAssistantMessage_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_descriptor.getNestedTypes().get(0);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcAssistantMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcAssistantMessage_descriptor,
        new java.lang.String[] { "Role", "Content", "ReasoningContent", "Name", "ToolCalls", "Refusal", "FunctionCall", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcDelta_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_descriptor.getNestedTypes().get(1);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcDelta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcChatCompletionChoice_GrpcDelta_descriptor,
        new java.lang.String[] { "Role", "Content", "ReasoningContent", "ToolCalls", "FunctionCall", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_descriptor.getNestedTypes().get(1);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_descriptor,
        new java.lang.String[] { "Id", "Index", "Type", "Function", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_GrpcFunctionCall_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_descriptor.getNestedTypes().get(0);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_GrpcFunctionCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcToolCall_GrpcFunctionCall_descriptor,
        new java.lang.String[] { "Name", "Arguments", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_descriptor.getNestedTypes().get(2);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_descriptor,
        new java.lang.String[] { "TotalTokens", "PromptTokens", "PromptTokensDetails", "CompletionTokens", "CompletionTokensDetails", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcPromptTokensDetails_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_descriptor.getNestedTypes().get(0);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcPromptTokensDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcPromptTokensDetails_descriptor,
        new java.lang.String[] { "CachedTokens", });
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcCompletionTokensDetails_descriptor =
      internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_descriptor.getNestedTypes().get(1);
    internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcCompletionTokensDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_v1_GrpcChatCompletionResponse_GrpcUsage_GrpcCompletionTokensDetails_descriptor,
        new java.lang.String[] { "ReasoningTokens", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
