// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package org.ai.aidemo.proto;

public interface GrpcChatCompletionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.v1.GrpcChatCompletionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 created = 2;</code>
   * @return The created.
   */
  int getCreated();

  /**
   * <code>optional string model = 3;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 3;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 3;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>repeated .chat.v1.GrpcChatCompletionResponse.GrpcChatCompletionChoice choices = 4;</code>
   */
  java.util.List<org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcChatCompletionChoice> 
      getChoicesList();
  /**
   * <code>repeated .chat.v1.GrpcChatCompletionResponse.GrpcChatCompletionChoice choices = 4;</code>
   */
  org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcChatCompletionChoice getChoices(int index);
  /**
   * <code>repeated .chat.v1.GrpcChatCompletionResponse.GrpcChatCompletionChoice choices = 4;</code>
   */
  int getChoicesCount();
  /**
   * <code>repeated .chat.v1.GrpcChatCompletionResponse.GrpcChatCompletionChoice choices = 4;</code>
   */
  java.util.List<? extends org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcChatCompletionChoiceOrBuilder> 
      getChoicesOrBuilderList();
  /**
   * <code>repeated .chat.v1.GrpcChatCompletionResponse.GrpcChatCompletionChoice choices = 4;</code>
   */
  org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcChatCompletionChoiceOrBuilder getChoicesOrBuilder(
      int index);

  /**
   * <code>optional .chat.v1.GrpcChatCompletionResponse.GrpcUsage usage = 5;</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <code>optional .chat.v1.GrpcChatCompletionResponse.GrpcUsage usage = 5;</code>
   * @return The usage.
   */
  org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcUsage getUsage();
  /**
   * <code>optional .chat.v1.GrpcChatCompletionResponse.GrpcUsage usage = 5;</code>
   */
  org.ai.aidemo.proto.GrpcChatCompletionResponse.GrpcUsageOrBuilder getUsageOrBuilder();

  /**
   * <code>optional string systemFingerprint = 6;</code>
   * @return Whether the systemFingerprint field is set.
   */
  boolean hasSystemFingerprint();
  /**
   * <code>optional string systemFingerprint = 6;</code>
   * @return The systemFingerprint.
   */
  java.lang.String getSystemFingerprint();
  /**
   * <code>optional string systemFingerprint = 6;</code>
   * @return The bytes for systemFingerprint.
   */
  com.google.protobuf.ByteString
      getSystemFingerprintBytes();

  /**
   * <code>optional string serviceTier = 7;</code>
   * @return Whether the serviceTier field is set.
   */
  boolean hasServiceTier();
  /**
   * <code>optional string serviceTier = 7;</code>
   * @return The serviceTier.
   */
  java.lang.String getServiceTier();
  /**
   * <code>optional string serviceTier = 7;</code>
   * @return The bytes for serviceTier.
   */
  com.google.protobuf.ByteString
      getServiceTierBytes();
}
