// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package org.ai.aidemo.proto;

public interface GrpcChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.v1.GrpcChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>optional string session = 2;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>optional string session = 2;</code>
   * @return The session.
   */
  java.lang.String getSession();
  /**
   * <code>optional string session = 2;</code>
   * @return The bytes for session.
   */
  com.google.protobuf.ByteString
      getSessionBytes();

  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   * @return Whether the toolCallVo field is set.
   */
  boolean hasToolCallVo();
  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   * @return The toolCallVo.
   */
  org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getToolCallVo();
  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   */
  org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder getToolCallVoOrBuilder();

  /**
   * <code>bool isToolCallInProgress = 4;</code>
   * @return The isToolCallInProgress.
   */
  boolean getIsToolCallInProgress();

  /**
   * <code>bool isToolCallFinished = 5;</code>
   * @return The isToolCallFinished.
   */
  boolean getIsToolCallFinished();
}
