// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package org.ai.aidemo.proto;

/**
 * Protobuf type {@code chat.v1.GrpcChatRequest}
 */
public final class GrpcChatRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chat.v1.GrpcChatRequest)
    GrpcChatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GrpcChatRequest.class.getName());
  }
  // Use GrpcChatRequest.newBuilder() to construct.
  private GrpcChatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GrpcChatRequest() {
    query_ = "";
    session_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ai.aidemo.proto.GrpcChatRequest.class, org.ai.aidemo.proto.GrpcChatRequest.Builder.class);
  }

  public interface GrpcToolCallVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:chat.v1.GrpcChatRequest.GrpcToolCallVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string toolCallId = 1;</code>
     * @return Whether the toolCallId field is set.
     */
    boolean hasToolCallId();
    /**
     * <code>optional string toolCallId = 1;</code>
     * @return The toolCallId.
     */
    java.lang.String getToolCallId();
    /**
     * <code>optional string toolCallId = 1;</code>
     * @return The bytes for toolCallId.
     */
    com.google.protobuf.ByteString
        getToolCallIdBytes();

    /**
     * <code>optional string functionName = 2;</code>
     * @return Whether the functionName field is set.
     */
    boolean hasFunctionName();
    /**
     * <code>optional string functionName = 2;</code>
     * @return The functionName.
     */
    java.lang.String getFunctionName();
    /**
     * <code>optional string functionName = 2;</code>
     * @return The bytes for functionName.
     */
    com.google.protobuf.ByteString
        getFunctionNameBytes();

    /**
     * <code>optional string toolArguments = 3;</code>
     * @return Whether the toolArguments field is set.
     */
    boolean hasToolArguments();
    /**
     * <code>optional string toolArguments = 3;</code>
     * @return The toolArguments.
     */
    java.lang.String getToolArguments();
    /**
     * <code>optional string toolArguments = 3;</code>
     * @return The bytes for toolArguments.
     */
    com.google.protobuf.ByteString
        getToolArgumentsBytes();

    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return Whether the toolCallResult field is set.
     */
    boolean hasToolCallResult();
    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return The toolCallResult.
     */
    java.lang.String getToolCallResult();
    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return The bytes for toolCallResult.
     */
    com.google.protobuf.ByteString
        getToolCallResultBytes();
  }
  /**
   * Protobuf type {@code chat.v1.GrpcChatRequest.GrpcToolCallVo}
   */
  public static final class GrpcToolCallVo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:chat.v1.GrpcChatRequest.GrpcToolCallVo)
      GrpcToolCallVoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        GrpcToolCallVo.class.getName());
    }
    // Use GrpcToolCallVo.newBuilder() to construct.
    private GrpcToolCallVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GrpcToolCallVo() {
      toolCallId_ = "";
      functionName_ = "";
      toolArguments_ = "";
      toolCallResult_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.class, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder.class);
    }

    private int bitField0_;
    public static final int TOOLCALLID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toolCallId_ = "";
    /**
     * <code>optional string toolCallId = 1;</code>
     * @return Whether the toolCallId field is set.
     */
    @java.lang.Override
    public boolean hasToolCallId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string toolCallId = 1;</code>
     * @return The toolCallId.
     */
    @java.lang.Override
    public java.lang.String getToolCallId() {
      java.lang.Object ref = toolCallId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toolCallId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string toolCallId = 1;</code>
     * @return The bytes for toolCallId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToolCallIdBytes() {
      java.lang.Object ref = toolCallId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toolCallId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCTIONNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object functionName_ = "";
    /**
     * <code>optional string functionName = 2;</code>
     * @return Whether the functionName field is set.
     */
    @java.lang.Override
    public boolean hasFunctionName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string functionName = 2;</code>
     * @return The functionName.
     */
    @java.lang.Override
    public java.lang.String getFunctionName() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string functionName = 2;</code>
     * @return The bytes for functionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFunctionNameBytes() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOOLARGUMENTS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toolArguments_ = "";
    /**
     * <code>optional string toolArguments = 3;</code>
     * @return Whether the toolArguments field is set.
     */
    @java.lang.Override
    public boolean hasToolArguments() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string toolArguments = 3;</code>
     * @return The toolArguments.
     */
    @java.lang.Override
    public java.lang.String getToolArguments() {
      java.lang.Object ref = toolArguments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toolArguments_ = s;
        return s;
      }
    }
    /**
     * <code>optional string toolArguments = 3;</code>
     * @return The bytes for toolArguments.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToolArgumentsBytes() {
      java.lang.Object ref = toolArguments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toolArguments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOOLCALLRESULT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toolCallResult_ = "";
    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return Whether the toolCallResult field is set.
     */
    @java.lang.Override
    public boolean hasToolCallResult() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return The toolCallResult.
     */
    @java.lang.Override
    public java.lang.String getToolCallResult() {
      java.lang.Object ref = toolCallResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toolCallResult_ = s;
        return s;
      }
    }
    /**
     * <code>optional string toolCallResult = 4;</code>
     * @return The bytes for toolCallResult.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToolCallResultBytes() {
      java.lang.Object ref = toolCallResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toolCallResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, toolCallId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, functionName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, toolArguments_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, toolCallResult_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, toolCallId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, functionName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, toolArguments_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, toolCallResult_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo)) {
        return super.equals(obj);
      }
      org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo other = (org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo) obj;

      if (hasToolCallId() != other.hasToolCallId()) return false;
      if (hasToolCallId()) {
        if (!getToolCallId()
            .equals(other.getToolCallId())) return false;
      }
      if (hasFunctionName() != other.hasFunctionName()) return false;
      if (hasFunctionName()) {
        if (!getFunctionName()
            .equals(other.getFunctionName())) return false;
      }
      if (hasToolArguments() != other.hasToolArguments()) return false;
      if (hasToolArguments()) {
        if (!getToolArguments()
            .equals(other.getToolArguments())) return false;
      }
      if (hasToolCallResult() != other.hasToolCallResult()) return false;
      if (hasToolCallResult()) {
        if (!getToolCallResult()
            .equals(other.getToolCallResult())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToolCallId()) {
        hash = (37 * hash) + TOOLCALLID_FIELD_NUMBER;
        hash = (53 * hash) + getToolCallId().hashCode();
      }
      if (hasFunctionName()) {
        hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFunctionName().hashCode();
      }
      if (hasToolArguments()) {
        hash = (37 * hash) + TOOLARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getToolArguments().hashCode();
      }
      if (hasToolCallResult()) {
        hash = (37 * hash) + TOOLCALLRESULT_FIELD_NUMBER;
        hash = (53 * hash) + getToolCallResult().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chat.v1.GrpcChatRequest.GrpcToolCallVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:chat.v1.GrpcChatRequest.GrpcToolCallVo)
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.class, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder.class);
      }

      // Construct using org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        toolCallId_ = "";
        functionName_ = "";
        toolArguments_ = "";
        toolCallResult_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_GrpcToolCallVo_descriptor;
      }

      @java.lang.Override
      public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getDefaultInstanceForType() {
        return org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance();
      }

      @java.lang.Override
      public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo build() {
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo buildPartial() {
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo result = new org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.toolCallId_ = toolCallId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.functionName_ = functionName_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.toolArguments_ = toolArguments_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.toolCallResult_ = toolCallResult_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo) {
          return mergeFrom((org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo other) {
        if (other == org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance()) return this;
        if (other.hasToolCallId()) {
          toolCallId_ = other.toolCallId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFunctionName()) {
          functionName_ = other.functionName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasToolArguments()) {
          toolArguments_ = other.toolArguments_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasToolCallResult()) {
          toolCallResult_ = other.toolCallResult_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                toolCallId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                functionName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                toolArguments_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                toolCallResult_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object toolCallId_ = "";
      /**
       * <code>optional string toolCallId = 1;</code>
       * @return Whether the toolCallId field is set.
       */
      public boolean hasToolCallId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string toolCallId = 1;</code>
       * @return The toolCallId.
       */
      public java.lang.String getToolCallId() {
        java.lang.Object ref = toolCallId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toolCallId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toolCallId = 1;</code>
       * @return The bytes for toolCallId.
       */
      public com.google.protobuf.ByteString
          getToolCallIdBytes() {
        java.lang.Object ref = toolCallId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toolCallId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toolCallId = 1;</code>
       * @param value The toolCallId to set.
       * @return This builder for chaining.
       */
      public Builder setToolCallId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toolCallId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolCallId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToolCallId() {
        toolCallId_ = getDefaultInstance().getToolCallId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolCallId = 1;</code>
       * @param value The bytes for toolCallId to set.
       * @return This builder for chaining.
       */
      public Builder setToolCallIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toolCallId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object functionName_ = "";
      /**
       * <code>optional string functionName = 2;</code>
       * @return Whether the functionName field is set.
       */
      public boolean hasFunctionName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string functionName = 2;</code>
       * @return The functionName.
       */
      public java.lang.String getFunctionName() {
        java.lang.Object ref = functionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          functionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string functionName = 2;</code>
       * @return The bytes for functionName.
       */
      public com.google.protobuf.ByteString
          getFunctionNameBytes() {
        java.lang.Object ref = functionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          functionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string functionName = 2;</code>
       * @param value The functionName to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        functionName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string functionName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunctionName() {
        functionName_ = getDefaultInstance().getFunctionName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string functionName = 2;</code>
       * @param value The bytes for functionName to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        functionName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object toolArguments_ = "";
      /**
       * <code>optional string toolArguments = 3;</code>
       * @return Whether the toolArguments field is set.
       */
      public boolean hasToolArguments() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string toolArguments = 3;</code>
       * @return The toolArguments.
       */
      public java.lang.String getToolArguments() {
        java.lang.Object ref = toolArguments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toolArguments_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toolArguments = 3;</code>
       * @return The bytes for toolArguments.
       */
      public com.google.protobuf.ByteString
          getToolArgumentsBytes() {
        java.lang.Object ref = toolArguments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toolArguments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toolArguments = 3;</code>
       * @param value The toolArguments to set.
       * @return This builder for chaining.
       */
      public Builder setToolArguments(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toolArguments_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolArguments = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToolArguments() {
        toolArguments_ = getDefaultInstance().getToolArguments();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolArguments = 3;</code>
       * @param value The bytes for toolArguments to set.
       * @return This builder for chaining.
       */
      public Builder setToolArgumentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toolArguments_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object toolCallResult_ = "";
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @return Whether the toolCallResult field is set.
       */
      public boolean hasToolCallResult() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @return The toolCallResult.
       */
      public java.lang.String getToolCallResult() {
        java.lang.Object ref = toolCallResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toolCallResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @return The bytes for toolCallResult.
       */
      public com.google.protobuf.ByteString
          getToolCallResultBytes() {
        java.lang.Object ref = toolCallResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toolCallResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @param value The toolCallResult to set.
       * @return This builder for chaining.
       */
      public Builder setToolCallResult(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toolCallResult_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToolCallResult() {
        toolCallResult_ = getDefaultInstance().getToolCallResult();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string toolCallResult = 4;</code>
       * @param value The bytes for toolCallResult to set.
       * @return This builder for chaining.
       */
      public Builder setToolCallResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toolCallResult_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:chat.v1.GrpcChatRequest.GrpcToolCallVo)
    }

    // @@protoc_insertion_point(class_scope:chat.v1.GrpcChatRequest.GrpcToolCallVo)
    private static final org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo();
    }

    public static org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GrpcToolCallVo>
        PARSER = new com.google.protobuf.AbstractParser<GrpcToolCallVo>() {
      @java.lang.Override
      public GrpcToolCallVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GrpcToolCallVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GrpcToolCallVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int QUERY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object query_ = "";
  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object session_ = "";
  /**
   * <code>optional string session = 2;</code>
   * @return Whether the session field is set.
   */
  @java.lang.Override
  public boolean hasSession() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string session = 2;</code>
   * @return The session.
   */
  @java.lang.Override
  public java.lang.String getSession() {
    java.lang.Object ref = session_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      session_ = s;
      return s;
    }
  }
  /**
   * <code>optional string session = 2;</code>
   * @return The bytes for session.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionBytes() {
    java.lang.Object ref = session_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      session_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOOLCALLVO_FIELD_NUMBER = 3;
  private org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo toolCallVo_;
  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   * @return Whether the toolCallVo field is set.
   */
  @java.lang.Override
  public boolean hasToolCallVo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   * @return The toolCallVo.
   */
  @java.lang.Override
  public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getToolCallVo() {
    return toolCallVo_ == null ? org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance() : toolCallVo_;
  }
  /**
   * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
   */
  @java.lang.Override
  public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder getToolCallVoOrBuilder() {
    return toolCallVo_ == null ? org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance() : toolCallVo_;
  }

  public static final int ISTOOLCALLINPROGRESS_FIELD_NUMBER = 4;
  private boolean isToolCallInProgress_ = false;
  /**
   * <code>bool isToolCallInProgress = 4;</code>
   * @return The isToolCallInProgress.
   */
  @java.lang.Override
  public boolean getIsToolCallInProgress() {
    return isToolCallInProgress_;
  }

  public static final int ISTOOLCALLFINISHED_FIELD_NUMBER = 5;
  private boolean isToolCallFinished_ = false;
  /**
   * <code>bool isToolCallFinished = 5;</code>
   * @return The isToolCallFinished.
   */
  @java.lang.Override
  public boolean getIsToolCallFinished() {
    return isToolCallFinished_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(query_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, query_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, session_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getToolCallVo());
    }
    if (isToolCallInProgress_ != false) {
      output.writeBool(4, isToolCallInProgress_);
    }
    if (isToolCallFinished_ != false) {
      output.writeBool(5, isToolCallFinished_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(query_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, query_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, session_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getToolCallVo());
    }
    if (isToolCallInProgress_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isToolCallInProgress_);
    }
    if (isToolCallFinished_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isToolCallFinished_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ai.aidemo.proto.GrpcChatRequest)) {
      return super.equals(obj);
    }
    org.ai.aidemo.proto.GrpcChatRequest other = (org.ai.aidemo.proto.GrpcChatRequest) obj;

    if (!getQuery()
        .equals(other.getQuery())) return false;
    if (hasSession() != other.hasSession()) return false;
    if (hasSession()) {
      if (!getSession()
          .equals(other.getSession())) return false;
    }
    if (hasToolCallVo() != other.hasToolCallVo()) return false;
    if (hasToolCallVo()) {
      if (!getToolCallVo()
          .equals(other.getToolCallVo())) return false;
    }
    if (getIsToolCallInProgress()
        != other.getIsToolCallInProgress()) return false;
    if (getIsToolCallFinished()
        != other.getIsToolCallFinished()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    if (hasSession()) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
    }
    if (hasToolCallVo()) {
      hash = (37 * hash) + TOOLCALLVO_FIELD_NUMBER;
      hash = (53 * hash) + getToolCallVo().hashCode();
    }
    hash = (37 * hash) + ISTOOLCALLINPROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsToolCallInProgress());
    hash = (37 * hash) + ISTOOLCALLFINISHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsToolCallFinished());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.ai.aidemo.proto.GrpcChatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.ai.aidemo.proto.GrpcChatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.ai.aidemo.proto.GrpcChatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ai.aidemo.proto.GrpcChatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chat.v1.GrpcChatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chat.v1.GrpcChatRequest)
      org.ai.aidemo.proto.GrpcChatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ai.aidemo.proto.GrpcChatRequest.class, org.ai.aidemo.proto.GrpcChatRequest.Builder.class);
    }

    // Construct using org.ai.aidemo.proto.GrpcChatRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetToolCallVoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      query_ = "";
      session_ = "";
      toolCallVo_ = null;
      if (toolCallVoBuilder_ != null) {
        toolCallVoBuilder_.dispose();
        toolCallVoBuilder_ = null;
      }
      isToolCallInProgress_ = false;
      isToolCallFinished_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ai.aidemo.proto.Demo.internal_static_chat_v1_GrpcChatRequest_descriptor;
    }

    @java.lang.Override
    public org.ai.aidemo.proto.GrpcChatRequest getDefaultInstanceForType() {
      return org.ai.aidemo.proto.GrpcChatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.ai.aidemo.proto.GrpcChatRequest build() {
      org.ai.aidemo.proto.GrpcChatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ai.aidemo.proto.GrpcChatRequest buildPartial() {
      org.ai.aidemo.proto.GrpcChatRequest result = new org.ai.aidemo.proto.GrpcChatRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.ai.aidemo.proto.GrpcChatRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.query_ = query_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.session_ = session_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.toolCallVo_ = toolCallVoBuilder_ == null
            ? toolCallVo_
            : toolCallVoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isToolCallInProgress_ = isToolCallInProgress_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isToolCallFinished_ = isToolCallFinished_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ai.aidemo.proto.GrpcChatRequest) {
        return mergeFrom((org.ai.aidemo.proto.GrpcChatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ai.aidemo.proto.GrpcChatRequest other) {
      if (other == org.ai.aidemo.proto.GrpcChatRequest.getDefaultInstance()) return this;
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasSession()) {
        session_ = other.session_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasToolCallVo()) {
        mergeToolCallVo(other.getToolCallVo());
      }
      if (other.getIsToolCallInProgress() != false) {
        setIsToolCallInProgress(other.getIsToolCallInProgress());
      }
      if (other.getIsToolCallFinished() != false) {
        setIsToolCallFinished(other.getIsToolCallFinished());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              query_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              session_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetToolCallVoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              isToolCallInProgress_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isToolCallFinished_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object query_ = "";
    /**
     * <code>string query = 1;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string query = 1;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      query_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string query = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      query_ = getDefaultInstance().getQuery();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string query = 1;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      query_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object session_ = "";
    /**
     * <code>optional string session = 2;</code>
     * @return Whether the session field is set.
     */
    public boolean hasSession() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string session = 2;</code>
     * @return The session.
     */
    public java.lang.String getSession() {
      java.lang.Object ref = session_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        session_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string session = 2;</code>
     * @return The bytes for session.
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      java.lang.Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string session = 2;</code>
     * @param value The session to set.
     * @return This builder for chaining.
     */
    public Builder setSession(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      session_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string session = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSession() {
      session_ = getDefaultInstance().getSession();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string session = 2;</code>
     * @param value The bytes for session to set.
     * @return This builder for chaining.
     */
    public Builder setSessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      session_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo toolCallVo_;
    private com.google.protobuf.SingleFieldBuilder<
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder> toolCallVoBuilder_;
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     * @return Whether the toolCallVo field is set.
     */
    public boolean hasToolCallVo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     * @return The toolCallVo.
     */
    public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo getToolCallVo() {
      if (toolCallVoBuilder_ == null) {
        return toolCallVo_ == null ? org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance() : toolCallVo_;
      } else {
        return toolCallVoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public Builder setToolCallVo(org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo value) {
      if (toolCallVoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toolCallVo_ = value;
      } else {
        toolCallVoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public Builder setToolCallVo(
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder builderForValue) {
      if (toolCallVoBuilder_ == null) {
        toolCallVo_ = builderForValue.build();
      } else {
        toolCallVoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public Builder mergeToolCallVo(org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo value) {
      if (toolCallVoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          toolCallVo_ != null &&
          toolCallVo_ != org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance()) {
          getToolCallVoBuilder().mergeFrom(value);
        } else {
          toolCallVo_ = value;
        }
      } else {
        toolCallVoBuilder_.mergeFrom(value);
      }
      if (toolCallVo_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public Builder clearToolCallVo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      toolCallVo_ = null;
      if (toolCallVoBuilder_ != null) {
        toolCallVoBuilder_.dispose();
        toolCallVoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder getToolCallVoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetToolCallVoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    public org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder getToolCallVoOrBuilder() {
      if (toolCallVoBuilder_ != null) {
        return toolCallVoBuilder_.getMessageOrBuilder();
      } else {
        return toolCallVo_ == null ?
            org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.getDefaultInstance() : toolCallVo_;
      }
    }
    /**
     * <code>optional .chat.v1.GrpcChatRequest.GrpcToolCallVo toolCallVo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder> 
        internalGetToolCallVoFieldBuilder() {
      if (toolCallVoBuilder_ == null) {
        toolCallVoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVo.Builder, org.ai.aidemo.proto.GrpcChatRequest.GrpcToolCallVoOrBuilder>(
                getToolCallVo(),
                getParentForChildren(),
                isClean());
        toolCallVo_ = null;
      }
      return toolCallVoBuilder_;
    }

    private boolean isToolCallInProgress_ ;
    /**
     * <code>bool isToolCallInProgress = 4;</code>
     * @return The isToolCallInProgress.
     */
    @java.lang.Override
    public boolean getIsToolCallInProgress() {
      return isToolCallInProgress_;
    }
    /**
     * <code>bool isToolCallInProgress = 4;</code>
     * @param value The isToolCallInProgress to set.
     * @return This builder for chaining.
     */
    public Builder setIsToolCallInProgress(boolean value) {

      isToolCallInProgress_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool isToolCallInProgress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsToolCallInProgress() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isToolCallInProgress_ = false;
      onChanged();
      return this;
    }

    private boolean isToolCallFinished_ ;
    /**
     * <code>bool isToolCallFinished = 5;</code>
     * @return The isToolCallFinished.
     */
    @java.lang.Override
    public boolean getIsToolCallFinished() {
      return isToolCallFinished_;
    }
    /**
     * <code>bool isToolCallFinished = 5;</code>
     * @param value The isToolCallFinished to set.
     * @return This builder for chaining.
     */
    public Builder setIsToolCallFinished(boolean value) {

      isToolCallFinished_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool isToolCallFinished = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsToolCallFinished() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isToolCallFinished_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:chat.v1.GrpcChatRequest)
  }

  // @@protoc_insertion_point(class_scope:chat.v1.GrpcChatRequest)
  private static final org.ai.aidemo.proto.GrpcChatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ai.aidemo.proto.GrpcChatRequest();
  }

  public static org.ai.aidemo.proto.GrpcChatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcChatRequest>
      PARSER = new com.google.protobuf.AbstractParser<GrpcChatRequest>() {
    @java.lang.Override
    public GrpcChatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GrpcChatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcChatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ai.aidemo.proto.GrpcChatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

